### ISSUE TITLE
Hitting Enter while entering SongID for filter causes inconsistent behavior

### ISSUE THREAD

**Issue by torzod** [iswilljr/enter-search-gd#3]
While searching for levels with a certain song, if you hit enter in the song id, it may search for levels using a single-digit song id, search for levels using the inputted song id, or search for the level with the same id as the song you have input. this behavior seems very inconsistent, even with only this mod + its dependencies installed, and is likely unintended.

**Comment by iswilljr** [comment]
it seems to be how the song filter works, the song id is not updated until you close the popup.
